name: 'Check Required Jobs'
description: 'Check if all required jobs in CI workflow were successful'
author: 'Ivan Pavlovic'
inputs:
  github-token:
    description: 'Github app token'
    required: true
outputs:
  result:
    description: 'The result of the check'

runs:
  using: 'node20'
  main: 'dist/index.js'